-- 1. Criar a tabela 'inventory'
CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  "minQuantity" INTEGER NOT NULL DEFAULT 0,
  "updatedBy" TEXT DEFAULT 'Admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- 2. Habilitar RLS (Row Level Security) - Permitindo acesso público apenas para simplificar esse tutorial
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura pública" ON inventory
  FOR SELECT USING (true);

CREATE POLICY "Permitir inserção pública" ON inventory
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir atualização pública" ON inventory
  FOR UPDATE USING (true);

CREATE POLICY "Permitir remoção pública" ON inventory
  FOR DELETE USING (true);

-- 3. Ativar Replica Identity para o Real-time enviar toda a linha alterada
ALTER TABLE inventory REPLICA IDENTITY FULL;

-- 4. Inserir dados de exemplo (opcional)
INSERT INTO inventory (name, category, quantity, "minQuantity") VALUES 
  ('Roteador Wi-Fi 6', 'Equipamento', 45, 10),
  ('Cabo de Fibra Óptica (m)', 'Cabeamento', 1200, 500),
  ('Modem ONT GPON', 'Equipamento', 5, 20),
  ('Conector APC', 'Acessório', 300, 100);
