-- 1. Remover tabela antiga (opcional, caso queira limpar)
DROP TABLE IF EXISTS inventory;

-- 2. Criar a nova tabela 'orders' (Pedidos)
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'pedido', -- Valores: 'pedido', 'separacao', 'disponivel'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- 3. Habilitar RLS (Row Level Security) - Permitindo acesso público
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura pública" ON orders
  FOR SELECT USING (true);

CREATE POLICY "Permitir inserção pública" ON orders
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir atualização pública" ON orders
  FOR UPDATE USING (true);

CREATE POLICY "Permitir remoção pública" ON orders
  FOR DELETE USING (true);

-- 4. Ativar Replica Identity para o Real-time enviar toda a linha alterada
ALTER TABLE orders REPLICA IDENTITY FULL;

-- Adicionar a tabela à publicação do supabase_realtime
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;

-- 5. Inserir dados de exemplo para testar a TV
INSERT INTO orders (employee, description, status) VALUES 
  ('Luan Fernandes', '2x Roteador Wi-Fi 6', 'pedido'),
  ('Maria Silva', '50m Cabo Drop', 'separacao'),
  ('João Souza', '1x Modem GPON', 'disponivel');
